[project]
name = "wikipediascraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "ipykernel>=7.2.0",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "nltk>=3.9.4",
    "pip>=26.0.1",
    "requests>=2.33.0",
    "wordcloud>=1.9.6",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv]
package = true

[tool.pytest.ini_options]
addopts = "--cov=wikipediascraper --cov-report=term-missing --cov-report=html"
markers = [
    "integration: mark test as an integration test hitting live APIs",
]

[tool.pyright]
exclude = [
    ".venv",
    "tests",
    "build"
]

[dependency-groups]
dev = [
    "icecream>=2.2.0",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
